export const LESSON_CATEGORIES = [
  {
    id: 1,
    slug: 'basics',
    icon: '\uD83C\uDFAF',
    nameKo: '업무자동화 기초',
    nameEn: 'Automation Basics',
    descKo: '업무자동화의 개념과 필요성, 기본 원리를 학습합니다.',
    descEn: 'Learn the concepts, necessity, and basic principles of work automation.',
    level: 'beginner',
    lessons: [
      { slug: 'what-is-automation', titleKo: '업무자동화란 무엇인가', titleEn: 'What is Work Automation', duration: 15 },
      { slug: 'why-automate', titleKo: '왜 자동화해야 하는가', titleEn: 'Why Automate', duration: 12 },
      { slug: 'automation-types', titleKo: '자동화의 유형과 분류', titleEn: 'Types of Automation', duration: 18 },
      { slug: 'getting-started', titleKo: '자동화 시작하기', titleEn: 'Getting Started', duration: 15 },
      { slug: 'automation-mindset', titleKo: '자동화 마인드셋', titleEn: 'Automation Mindset', duration: 10 },
    ],
  },
  {
    id: 2,
    slug: 'excel',
    icon: '\uD83D\uDCCA',
    nameKo: 'Excel/스프레드시트 자동화',
    nameEn: 'Excel/Spreadsheet Automation',
    descKo: 'Excel 수식, 매크로, VBA를 활용한 업무 자동화를 학습합니다.',
    descEn: 'Learn work automation using Excel formulas, macros, and VBA.',
    level: 'beginner',
    lessons: [
      { slug: 'excel-formulas', titleKo: '핵심 Excel 수식 마스터', titleEn: 'Master Essential Excel Formulas', duration: 20 },
      { slug: 'conditional-formatting', titleKo: '조건부 서식과 데이터 유효성', titleEn: 'Conditional Formatting & Validation', duration: 15 },
      { slug: 'pivot-tables', titleKo: '피벗 테이블 활용', titleEn: 'Pivot Tables', duration: 18 },
      { slug: 'vba-basics', titleKo: 'VBA 매크로 기초', titleEn: 'VBA Macro Basics', duration: 25 },
      { slug: 'vba-automation', titleKo: 'VBA 실전 자동화', titleEn: 'VBA Practical Automation', duration: 30 },
      { slug: 'google-sheets', titleKo: 'Google Sheets 자동화', titleEn: 'Google Sheets Automation', duration: 20 },
    ],
  },
  {
    id: 3,
    slug: 'python',
    icon: '\uD83D\uDC0D',
    nameKo: 'Python 업무자동화',
    nameEn: 'Python Work Automation',
    descKo: 'Python을 활용한 파일 처리, 웹 스크래핑, 자동화 스크립트를 학습합니다.',
    descEn: 'Learn file processing, web scraping, and automation scripts with Python.',
    level: 'intermediate',
    lessons: [
      { slug: 'python-setup', titleKo: 'Python 환경 설정', titleEn: 'Python Setup', duration: 15 },
      { slug: 'file-automation', titleKo: '파일/폴더 자동화', titleEn: 'File & Folder Automation', duration: 25 },
      { slug: 'excel-with-python', titleKo: 'Python으로 Excel 다루기', titleEn: 'Excel with Python', duration: 30 },
      { slug: 'web-scraping', titleKo: '웹 스크래핑 기초', titleEn: 'Web Scraping Basics', duration: 25 },
      { slug: 'email-automation', titleKo: '이메일 자동화', titleEn: 'Email Automation', duration: 20 },
      { slug: 'pdf-automation', titleKo: 'PDF 자동 처리', titleEn: 'PDF Automation', duration: 20 },
      { slug: 'scheduling', titleKo: '작업 스케줄링', titleEn: 'Task Scheduling', duration: 15 },
    ],
  },
  {
    id: 4,
    slug: 'rpa',
    icon: '\uD83E\uDD16',
    nameKo: 'RPA 도구 활용',
    nameEn: 'RPA Tools',
    descKo: 'UiPath, Power Automate 등 RPA 도구를 활용한 업무 자동화를 학습합니다.',
    descEn: 'Learn work automation using RPA tools like UiPath and Power Automate.',
    level: 'intermediate',
    lessons: [
      { slug: 'rpa-overview', titleKo: 'RPA 개요와 원리', titleEn: 'RPA Overview & Principles', duration: 15 },
      { slug: 'uipath-basics', titleKo: 'UiPath 기초', titleEn: 'UiPath Basics', duration: 30 },
      { slug: 'power-automate', titleKo: 'Power Automate 활용', titleEn: 'Power Automate', duration: 25 },
      { slug: 'rpa-best-practices', titleKo: 'RPA 설계 모범 사례', titleEn: 'RPA Best Practices', duration: 20 },
      { slug: 'rpa-deployment', titleKo: 'RPA 배포와 관리', titleEn: 'RPA Deployment & Management', duration: 20 },
    ],
  },
  {
    id: 5,
    slug: 'nocode',
    icon: '\u26A1',
    nameKo: '노코드/로코드 자동화',
    nameEn: 'No-Code/Low-Code Automation',
    descKo: 'Zapier, Make, n8n 등 노코드 도구로 업무를 자동화합니다.',
    descEn: 'Automate work using no-code tools like Zapier, Make, and n8n.',
    level: 'beginner',
    lessons: [
      { slug: 'nocode-intro', titleKo: '노코드/로코드 소개', titleEn: 'No-Code/Low-Code Introduction', duration: 12 },
      { slug: 'zapier', titleKo: 'Zapier 활용법', titleEn: 'Using Zapier', duration: 25 },
      { slug: 'make', titleKo: 'Make(Integromat) 활용', titleEn: 'Using Make (Integromat)', duration: 25 },
      { slug: 'n8n', titleKo: 'n8n 워크플로우', titleEn: 'n8n Workflows', duration: 20 },
      { slug: 'nocode-comparison', titleKo: '노코드 도구 비교', titleEn: 'No-Code Tool Comparison', duration: 15 },
    ],
  },
  {
    id: 6,
    slug: 'ai',
    icon: '\uD83E\uDDE0',
    nameKo: 'AI 활용 업무자동화',
    nameEn: 'AI-Powered Automation',
    descKo: 'ChatGPT, Claude 등 AI를 활용한 업무 자동화 기법을 학습합니다.',
    descEn: 'Learn automation techniques using AI tools like ChatGPT and Claude.',
    level: 'advanced',
    lessons: [
      { slug: 'ai-automation-intro', titleKo: 'AI 자동화 소개', titleEn: 'AI Automation Introduction', duration: 15 },
      { slug: 'chatgpt-automation', titleKo: 'ChatGPT 업무 활용', titleEn: 'ChatGPT for Work', duration: 25 },
      { slug: 'ai-document-processing', titleKo: 'AI 문서 처리', titleEn: 'AI Document Processing', duration: 20 },
      { slug: 'ai-data-analysis', titleKo: 'AI 데이터 분석', titleEn: 'AI Data Analysis', duration: 25 },
      { slug: 'prompt-engineering', titleKo: '프롬프트 엔지니어링', titleEn: 'Prompt Engineering', duration: 20 },
      { slug: 'ai-workflow-integration', titleKo: 'AI 워크플로우 통합', titleEn: 'AI Workflow Integration', duration: 20 },
    ],
  },
  {
    id: 7,
    slug: 'document',
    icon: '\uD83D\uDCC4',
    nameKo: '문서/이메일 자동화',
    nameEn: 'Document & Email Automation',
    descKo: '문서 생성, 이메일 발송, 보고서 자동화를 학습합니다.',
    descEn: 'Learn document generation, email delivery, and report automation.',
    level: 'intermediate',
    lessons: [
      { slug: 'document-templates', titleKo: '문서 템플릿 자동화', titleEn: 'Document Template Automation', duration: 20 },
      { slug: 'email-templates', titleKo: '이메일 템플릿과 자동 발송', titleEn: 'Email Templates & Auto-Send', duration: 18 },
      { slug: 'report-generation', titleKo: '보고서 자동 생성', titleEn: 'Automatic Report Generation', duration: 25 },
      { slug: 'ocr-digitization', titleKo: 'OCR과 문서 디지털화', titleEn: 'OCR & Document Digitization', duration: 20 },
    ],
  },
  {
    id: 8,
    slug: 'data',
    icon: '\uD83D\uDCC8',
    nameKo: '데이터 수집/분석 자동화',
    nameEn: 'Data Collection & Analysis Automation',
    descKo: '데이터 수집, 정제, 시각화 자동화를 학습합니다.',
    descEn: 'Learn automated data collection, cleaning, and visualization.',
    level: 'intermediate',
    lessons: [
      { slug: 'data-collection', titleKo: '데이터 자동 수집', titleEn: 'Automated Data Collection', duration: 25 },
      { slug: 'data-cleaning', titleKo: '데이터 정제 자동화', titleEn: 'Automated Data Cleaning', duration: 20 },
      { slug: 'data-visualization', titleKo: '자동화된 데이터 시각화', titleEn: 'Automated Data Visualization', duration: 22 },
      { slug: 'dashboard-automation', titleKo: '대시보드 자동화', titleEn: 'Dashboard Automation', duration: 25 },
    ],
  },
  {
    id: 9,
    slug: 'workflow',
    icon: '\uD83D\uDD04',
    nameKo: '워크플로우 설계',
    nameEn: 'Workflow Design',
    descKo: '효율적인 업무 프로세스 설계와 최적화를 학습합니다.',
    descEn: 'Learn efficient business process design and optimization.',
    level: 'advanced',
    lessons: [
      { slug: 'process-mapping', titleKo: '프로세스 매핑', titleEn: 'Process Mapping', duration: 20 },
      { slug: 'workflow-optimization', titleKo: '워크플로우 최적화', titleEn: 'Workflow Optimization', duration: 22 },
      { slug: 'error-handling', titleKo: '오류 처리와 예외 관리', titleEn: 'Error Handling & Exception Management', duration: 18 },
      { slug: 'monitoring', titleKo: '자동화 모니터링', titleEn: 'Automation Monitoring', duration: 18 },
    ],
  },
  {
    id: 10,
    slug: 'projects',
    icon: '\uD83D\uDE80',
    nameKo: '실전 프로젝트',
    nameEn: 'Real-World Projects',
    descKo: '실제 업무 시나리오에 기반한 종합 자동화 프로젝트를 수행합니다.',
    descEn: 'Complete comprehensive automation projects based on real work scenarios.',
    level: 'advanced',
    lessons: [
      { slug: 'hr-automation', titleKo: '인사/급여 자동화 프로젝트', titleEn: 'HR & Payroll Automation Project', duration: 40 },
      { slug: 'sales-reporting', titleKo: '매출 보고서 자동화 프로젝트', titleEn: 'Sales Report Automation Project', duration: 35 },
      { slug: 'customer-service', titleKo: '고객 서비스 자동화 프로젝트', titleEn: 'Customer Service Automation Project', duration: 35 },
      { slug: 'full-stack-automation', titleKo: '풀스택 업무자동화 프로젝트', titleEn: 'Full-Stack Automation Project', duration: 45 },
    ],
  },
];

export function getCategoryBySlug(slug) {
  return LESSON_CATEGORIES.find(c => c.slug === slug);
}

export function getLessonBySlug(categorySlug, lessonSlug) {
  const category = getCategoryBySlug(categorySlug);
  if (!category) return null;
  return category.lessons.find(l => l.slug === lessonSlug);
}

export function getTotalLessonCount() {
  return LESSON_CATEGORIES.reduce((acc, cat) => acc + cat.lessons.length, 0);
}
